# Generated by Django 4.2.4 on 2023-08-26 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampoProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('imagem', 'Imagem'), ('arquivo', 'Arquivo'), ('booleano', 'Booleano')], max_length=10)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ValorCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='propostas/imagens/%Y/%m/')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='propostas/arquivos/%Y/%m/')),
                ('booleano', models.BooleanField(blank=True, null=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Propostas.campoproposta')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Propostas.proposta')),
            ],
        ),
        migrations.AddField(
            model_name='proposta',
            name='campos',
            field=models.ManyToManyField(through='Propostas.ValorCampo', to='Propostas.campoproposta'),
        ),
    ]
