# Generated by Django 4.2.4 on 2023-08-31 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Propostas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valorcampo',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='valorcampo',
            name='booleano',
        ),
        migrations.RemoveField(
            model_name='valorcampo',
            name='imagem',
        ),
        migrations.AddField(
            model_name='proposta',
            name='proposta_aceita',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='campoproposta',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto')], max_length=10),
        ),
    ]
